-- 1. Таблица Пользователей (users)
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       full_name VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 2. Таблица Счетов (accounts)
CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          balance NUMERIC(19, 2) NOT NULL,
                          currency VARCHAR(3) NOT NULL,
                          status VARCHAR(255) NOT NULL,
                          version BIGINT NOT NULL,
                          created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                          CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 3. Таблица Транзакций (transactions)
CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              from_account_id BIGINT,
                              to_account_id BIGINT,
                              amount NUMERIC(19, 2) NOT NULL,
                              currency VARCHAR(3) NOT NULL,
                              type VARCHAR(255) NOT NULL,
                              status VARCHAR(255) NOT NULL,
                              idempotency_key VARCHAR(255) NOT NULL UNIQUE,
                              created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                              CONSTRAINT fk_transactions_from_account FOREIGN KEY (from_account_id) REFERENCES accounts (id),
                              CONSTRAINT fk_transactions_to_account FOREIGN KEY (to_account_id) REFERENCES accounts (id)
);

-- 4. Таблица Refresh-токенов (refresh_tokens)
CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                token VARCHAR(255) NOT NULL UNIQUE,
                                expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

